name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsday"
database_id = "1335f5ff-49db-401b-bd52-993c7f5d38b3"
